<?php

namespace Tests\Feature;

use App\Reply;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class ThreadControllerTest extends TestCase
{
    use DatabaseMigrations;


    /**
     * @var \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed
     */
    private $thread;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory('App\Thread')->create();
    }

    /**
     * @test
     */
    public function a_user_can_see_all_threads(){
        $this->withoutExceptionHandling();


        $response = $this->get('/threads');
        $response->assertStatus(200);
        $response->assertSee($this->thread->title);
    }

    /**
     * @test
     **/
    public function a_user_can_see_single_thread()
    {
        $this->withoutExceptionHandling();

        $response = $this->get("/threads/{$this->thread->id}");

        $response->assertSee($this->thread->title);
    }

    /**
     * @test
     **/
    public function a_user_can_see_replies_that_are_associated_with_a_thread()
    {
        $this->withoutExceptionHandling();

        $reply = factory(Reply::class)->create(['thread_id' => $this->thread->id]);

        $this->get('/threads/' . $this->thread->id)
            ->assertSee($reply->body);
    }


}
