<?php

namespace Tests\Unit;

use App\Reply;
use App\Thread;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;


class ThreadTest extends TestCase
{
    use DatabaseMigrations;

    /**
     * @var \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed
     */
    private $thread;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory(Thread::class)->create();
    }

    /**
     * @test
     **/
    public function a_thread_have_replies()
    {
        $reply = factory(Reply::class)->create(['thread_id' => $this->thread->id]);
        $this->assertInstanceOf(Reply::class, $this->thread->replies->first());
    }




}
